name: Run it
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Zalenium
        uses: ajinx/zalenium@1.1
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: curl -sSL http://localhost:4444/wd/hub/status
      - run: | 
          pytest --splinter-remote-url=http://localhost:4444/wd/hub \
            --splinter-webdriver=remote \
            -k not_installed
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: reports
          path: |
            *.html
            tests.*/*.html
            tests.*/*.png
