name: Run it
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    services:
      selenium-service:
        image: selenium/standalone-chrome:4.0.0-beta-3-prerelease-20210402
        ports:
          - 4444:4444
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: curl -sSL http://localhost:4444/wd/hub/status
        name: Check if selenium up
      - run: | 
          pytest --splinter-remote-url=http://localhost:4444/wd/hub  --splinter-webdriver=remote  -k not_installed
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: reports
          path: |
            *.html
            tests.*/*.html
            tests.*/*.png
